version: '3.9'
services:
  database:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./wealthflow-api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wealthflow-network

  database_test:
    image: postgres:16
    container_name: postgres_test
    ports:
      - "5433:5432"
    env_file:
      - ./wealthflow-api/.env.test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - wealthflow-network

volumes:
  postgres_data:
  postgres_test_data:

networks:
  wealthflow-network:
